"""empty message

Revision ID: 9e5b2e7972f7
Revises: 9162ee64d489
Create Date: 2025-01-04 21:51:09.890078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5b2e7972f7'
down_revision = '9162ee64d489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('experience_requirement', sa.String(length=50), nullable=False),
    sa.Column('about_guide', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_column('services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('services')
    # ### end Alembic commands ###
