"""Add booking_length and daily_rate to Service model

Revision ID: 93148ec91e0f
Revises: 35c5da24f367
Create Date: 2025-02-09 17:45:27.165219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93148ec91e0f'
down_revision = '35c5da24f367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('daily_rate')
        batch_op.drop_column('booking_length')

    # ### end Alembic commands ###
