"""empty message

Revision ID: fe0bbc2b94fa
Revises: 93148ec91e0f
Create Date: 2025-02-09 18:13:43.310433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0bbc2b94fa'
down_revision = '93148ec91e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('booking_length')
        batch_op.drop_column('daily_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_rate', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('booking_length', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
